const data = {
  event_type:'boda',
  nombre_novia:'Mariam',
  nombre_novio:'Juan Carlos',
  nombre_papa_novia:'',
  nombre_mama_novia:'',
  nombre_papa_novio:'',
  nombre_mama_novio:'',
  frase:'Quienes estan destinados a ser, Siempre acaban siendo.',
  img_header:'back.webp',
  img_fondo1:'',
  img_fondo2:'',
  fecha_dia:'11',
  fecha_mes:'Octubre',
  fecha_year:'2024',
  religiosa_hora:'17:00',
  religiosa_lugar:'Iglesia del señor de Chalma',
  religiosa_direccion:'Venustiano Carranza',
  religiosa_direccion_col:'Adolfo López Mateos',
  religiosa_direccion_cd:'Iguala de la Independencia',
  religiosa_ubicacion:'https://maps.app.goo.gl/Fb1qF3NeeexBbfcL8',
  recepcion_hora:'19:00',
  recepcion_lugar:'Rinconada Hotel Boutique',
  recepcion_direccion:'General Baltazar R. Leyva Mancilla, 19',
  recepcion_direccion_col:'Centro',
  recepcion_direccion_cd:'Iguala de la Independencia, Guerrero',
  recepcion_ubicacion:'https://maps.app.goo.gl/81dqrkE91nPJy78K7',
  confirmacion_novia:'',
  confirmacion_novio:'',
}

export default data